name: flutter iphone instrumentation test

# Perform action when code is pushed to the main branche
on:
  push:
    branches: [main]

jobs:
  iphone_instrumentation_test:
    runs-on: macOS-latest

    env:
      device: 'iPhone 13 Simulator \(15.2\)'

    steps:
      - name: List all simulators
        run: xcrun xctrace list devices

      - name: Get UDID device and Start Simulator
        run: |
          UDID=$(xcrun xctrace list devices | awk -F " " '/${{ env.device }}/ && length($5) > 1 {print $5}' | tr -d '()')
          echo $UDID
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
